#!/usr/bin/with-contenv bash

if [ "$ALLOW_DEBUG" == "true" ]
then
 echo "Allowing for debug"
 cat << EDO >> /etc/php/7.0/fpm/php.ini
[xdebug]
zend_extension="/usr/lib/php5/20121212/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.idekey=bonkers
xdebug.max_nesting_level=300
EDO
fi

mkdir -p /var/run/fpm

echo "This is really it"
exec /usr/sbin/php-fpm -F