#!/usr/bin/with-contenv bash

if [ "$PROXY" != "" ]
then
    SRCP=80
    DST=$PROXY
    DSTP=80
    TMP=`mktemp -d`
    BACK=$TMP/pipe.back
    SENT=$TMP/pipe.sent
    RCVD=$TMP/pipe.rcvd
    trap 'rm -rf "$TMP"' EXIT
    mkfifo -m 0600 "$BACK" "$SENT" "$RCVD"
    sed 's/^/ => /' <"$SENT" &
    sed 's/^/<=  /' <"$RCVD" &
    nc -l -p "$SRCP" <"$BACK" | tee "$SENT" | nc "$DST" "$DSTP" | tee "$RCVD" >"$BACK"
fi