#!/usr/bin/with-contenv bash

userId=$(stat -c '%u' /var/www/flagship-local/public_html/index.php)
groupId=$(stat -c '%g' /var/www/flagship-local/public_html/index.php)
oldUserId=$(id -u www-data)
oldGroupId=$(id -g www-data)

usermod -u $userId www-data
#groupmod -g $groupId www-data
#find / -user $oldUserId -exec chown -h $userId {} \;
#find / -group $oldGroupId -exec chgrp -h $groupId {} \;
#usermod -g $groupId www-data