#!/usr/bin/with-contenv bash

if [ "$STARTUP_SQL" != "" ]
then
    crontab -l > cron
    echo "* * * * * mysqldump -p123 -uadmin flagship --skip-lock-tables --single-transaction --hex-blob --quick > $STARTUP_SQL 2>/dev/null" >> cron
    crontab cron
    rm cron
    echo "BACKUP INITIALIZED"
else
    echo "BACKUP NOT INIT"
fi